Dev container setup
eclipse-velocitas/vehicle-app-template pull request #1
Opened 2023-09-11 12:14 UTC by glm2bg

2023-09-11 12:38 UTC, dennismeister93 requested changes
Please also add the required files for the root of the repo

2023-09-11 12:38 UTC, dennismeister93 commented on .devcontainer/scripts/postCreateCommand.sh
> +echo "### Install Velocitas CLI ${CLI_INSTALL_VERSION}    ###"
```suggestion
echo "### Install Velocitas CLI ${CLI_INSTALL_VERSION}                    ###"
```

2023-09-11 12:38 UTC, dennismeister93 commented on .devcontainer/scripts/postCreateCommand.sh
> +CLI_ASSET_NAME=velocitas-linux-${ARH}
```suggestion
CLI_ASSET_NAME=velocitas-linux-$(echo $1 | sed 's/amd64/x64/g')
```

Why did you change this? any specific reason?

2023-09-11 12:38 UTC, dennismeister93 commented on .devcontainer/scripts/configure-proxies.sh
> +exit 0
Add a new line at the end

2023-09-11 12:38 UTC, dennismeister93 commented on .devcontainer/Dockerfile
> +
Add only one new line at the end

2023-09-11 12:38 UTC, dennismeister93 commented on .devcontainer/scripts/postCreateCommand.sh
Please rename the file to "onCreateCommand" since it will be called onCreate and not "post"

2023-09-11 12:38 UTC, dennismeister93 commented on .devcontainer/scripts/configure-proxies.sh
> +echo "#######################################################"
You need to add the license header

2023-09-12 16:21 UTC, doosuu requested changes
Let's discuss how the Docker image for this repo is created. I suggest it should be located in devcontainer-base-images rather than here.

2023-09-12 16:21 UTC, doosuu commented on .devcontainer/Dockerfile
> +# Copyright (c) 2023 Robert Bosch GmbH and Microsoft Corporation
```suggestion
# Copyright (c) 2023 Contributors to the Eclipse Foundation
```

2023-09-12 16:21 UTC, doosuu commented on .devcontainer/devcontainer.json
> +    "name": "Vehicle app template",
```suggestion
    "name": "Vehicle App Template",
```

2023-09-12 16:21 UTC, doosuu commented on .devcontainer/devcontainer.json
> +	"onCreateCommand": "bash .devcontainer/scripts/postCreateCommand.sh",
Fix alignment

2023-09-12 16:21 UTC, doosuu commented on .devcontainer/scripts/postCreateCommand.sh
> +# Copyright (c) 2023 Robert Bosch GmbH
```suggestion
# Copyright (c) 2023 Contributors to the Eclipse Foundation
```

2023-09-12 16:21 UTC, doosuu commented on .devcontainer/scripts/postCreateCommand.sh
> +CLI_INSTALL_VERSION='v0.5.5' # reference a particular released version
Use latest?

2023-09-12 16:21 UTC, doosuu commented on .devcontainer/scripts/postCreateCommand.sh
> +ARH=$(uname -m)
```suggestion
ARCH=$(uname -m)
```

2023-09-27 12:55 UTC, doosuu requested changes

2023-09-28 22:08 UTC, doosuu requested changes

2023-09-29 08:29 UTC, doosuu approved these changes
LGTM

2023-09-29 08:30 UTC, doosuu requested changes
Branch still set to the working branch

2023-09-29 11:45 UTC, doosuu approved these changes
LGTM

2023-09-29 14:23 UTC, dennismeister93 approved these changes
lgtm

2023-10-09 14:21 UTC, merged