rename postCreate script and call velocitas create postStart
eclipse-velocitas/vehicle-app-template pull request #3
Opened 2023-10-11 08:28 UTC by MP91

2023-10-11 09:11 UTC, doosuu requested changes

2023-10-11 09:14 UTC, MP91 commented on .devcontainer/scripts/onCreateCommand.sh
> +sudo /home/vscode/configure-proxies.sh &> /home/vscode/configure-proxies.log
what lines do you see? for me the log is just empty...

2023-10-11 09:34 UTC, doosuu commented on .devcontainer/scripts/onCreateCommand.sh
> +sudo /home/vscode/configure-proxies.sh &> /home/vscode/configure-proxies.log
I see a lot of lines starting with "+" after printing the proxy settings, which isnt harmful but doesnt look good.

2023-10-11 10:10 UTC, MP91 commented on .devcontainer/scripts/onCreateCommand.sh
> +sudo /home/vscode/configure-proxies.sh &> /home/vscode/configure-proxies.log
but they should just be in the log or do you still see them in the terminal?

2023-10-11 10:52 UTC, doosuu commented on .devcontainer/scripts/onCreateCommand.sh
> +sudo /home/vscode/configure-proxies.sh &> /home/vscode/configure-proxies.log
Saw them on the terminal before the file redirect. File redirect is still fine for me to have a "clean" terminal

2023-10-11 10:55 UTC, doosuu commented on .devcontainer/scripts/postStartCommand.sh
> +velocitas create $VELOCITAS_CREATE_VALUES
Call it args/arguments?

```suggestion
velocitas create $VELOCITAS_CREATE_ARGS
```

2023-10-11 11:54 UTC, MP91 commented on .devcontainer/devcontainer.json
> +                "terminal.integrated.defaultProfile.linux": "zsh",
will be installed once the new baseimage is availabel due to the common-utils

2023-10-11 11:55 UTC, MP91 commented on .devcontainer/scripts/postStartCommand.sh
> +velocitas create $VELOCITAS_CREATE_VALUES
done

2023-10-11 12:00 UTC, MP91 commented on .devcontainer/devcontainer.json
> +                "terminal.integrated.defaultProfile.linux": "zsh",
need to wait for the sdk to be released anyhow

2023-10-17 08:17 UTC, MP91 commented on .devcontainer/devcontainer.json
> +                "terminal.integrated.defaultProfile.linux": "bash",
why not zsh?

2023-10-17 09:21 UTC, BjoernAtBosch commented on .devcontainer/scripts/postStartCommand.sh
> +"
Nice :-)

2023-10-18 07:15 UTC, mml5bg approved these changes
LGTM

2023-10-18 07:16 UTC, merged